"""Original interview bank, authored for Offer Quest. Run to regenerate JSON + SQL seed."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
questions = []
def add(category, rows):
    prefix = {'ML':'ml','AI/LLM':'ai','Python':'py','BQ':'bq'}[category]
    for i, row in enumerate(rows, 1):
        prompt, points = row
        questions.append(dict(id=f'{prefix}-{i:02}', category=category, difficulty='Hard' if i%4==0 else 'Medium', prompt=prompt, rubric=points.split('|')))
add('ML', [
('A churn model has 96% accuracy, but only 4% of customers churn. How would you decide whether it is useful?', 'Compare with the majority-class baseline|Inspect precision, recall, and PR-AUC|Choose a threshold using intervention cost|Validate on a future time window'),
('Your training AUC is 0.94 and validation AUC is 0.69. Design an investigation before changing the model.', 'Verify split and leakage|Inspect learning curves|Compare train and validation distributions|Test regularization or a simpler baseline'),
('A feature is missing for 40% of mobile users but 2% of desktop users. How would you handle it?', 'Investigate the data collection mechanism|Avoid assuming missingness is random|Fit imputation using training data only|Evaluate performance by device and missingness'),
('A fraud team can inspect 200 transactions daily. How should you evaluate and deploy a classifier?', 'Measure precision or lift at the review budget|Account for delayed fraud labels|Evaluate monetary utility and recall|Monitor selection feedback and changing prevalence'),
('You predict next-month revenue using customer activity. Describe a leakage-safe validation design.', 'Define the prediction timestamp|Exclude features unavailable at prediction|Use chronological validation|Respect repeated customers and label windows'),
('Why might a regularized linear model outperform a boosted tree on a new geography?', 'Discuss variance and sample size|Explain extrapolation and inductive bias|Compare distribution shift by geography|Propose held-out geography evaluation'),
('Two highly correlated features have unstable coefficients. What changes would you consider, and what do the coefficients still mean?', 'Explain multicollinearity|Discuss conditional coefficient interpretation|Compare ridge, feature removal, or combined features|Distinguish prediction stability from attribution'),
('A recommendation model improved offline NDCG but reduced user retention. What could explain the gap?', 'Question offline labels and selection bias|Distinguish short-term relevance from retention|Consider exposure, diversity, and feedback loops|Design a guarded online experiment'),
('How would you choose a probability threshold when a false negative costs ten times a false positive?', 'Relate threshold to calibrated expected cost|State assumptions behind a cost ratio|Validate calibration and prevalence|Include operational constraints and sensitivity analysis'),
('A model gives confident probabilities but is often wrong. How would you measure and fix calibration?', 'Use reliability curves and proper scoring rules|Evaluate held-out calibration|Compare Platt scaling and isotonic regression|Check calibration across segments and over time'),
('Design a baseline for predicting demand for a new product with very little history.', 'Use analogous products and metadata|Define cold-start and temporal holdouts|Compare simple seasonal or pooled baselines|Quantify uncertainty and update with evidence'),
('A random forest and logistic regression have equal AUC. How would you choose between them?', 'Compare calibration and operating-point utility|Consider latency and maintenance|Consider interpretability and stability|Quantify uncertainty in the comparison'),
('Your dataset has multiple rows per patient. Explain why a random row split can mislead.', 'Recognize identity leakage and within-patient dependence|Split at the patient or deployment-relevant unit|Keep preprocessing inside the split|Consider temporal generalization'),
('How would you detect label leakage when a suspicious feature dramatically improves performance?', 'Audit feature lineage and availability timestamps|Ablate the feature|Simulate production feature generation|Look for proxies for post-outcome actions'),
('An experiment shows a 2% lift with a wide confidence interval. How should the team interpret it?', 'Separate point estimate from uncertainty|Discuss practical significance|Check randomization and power|Avoid treating nonsignificance as proof of no effect'),
('You have 500 labeled examples and a million unlabeled examples. Propose a learning strategy.', 'Start with a validated simple baseline|Consider active learning or representation transfer|Discuss pseudo-label error amplification|Keep a representative untouched evaluation set'),
('How would you select features when the dataset has more columns than observations?', 'Use regularization or dimensionality reduction|Perform selection within cross-validation|Check stability across resamples|Use domain knowledge and simpler baselines'),
('Explain when standardizing features changes a model and when it usually does not.', 'Connect scaling to distance and regularization|Explain linear or gradient optimization effects|Explain tree split ordering invariance|Fit transformation on training data only'),
('A deployed model loses precision while recall is stable. What would you investigate?', 'Check base-rate changes|Inspect threshold and calibration|Check label delay and instrumentation|Compare score distributions and segment mix'),
('How would you evaluate an anomaly detector when labels are sparse and biased toward previously investigated cases?', 'Recognize verification bias|Use a sampled review set|Evaluate at a fixed investigation budget|Combine expert review with downstream utility'),
('A business wants one number to compare forecasts across large and tiny stores. What metric would you recommend?', 'Discuss scale dependence|Explain MAPE problems near zero|Consider weighted absolute error or scaled errors|Report segment results alongside the aggregate'),
('Describe how bootstrap confidence intervals could go wrong for daily sales observations.', 'Identify serial dependence|Use block or appropriate cluster resampling|Preserve the sampling unit|Discuss nonstationarity and limited history'),
('A feature has high permutation importance but low business plausibility. What would you do?', 'Audit leakage and proxies|Discuss correlated-feature effects|Repeat on held-out segments|Avoid treating importance as causality'),
('Your classifier works poorly for a small customer group. How would you improve it without hiding aggregate regressions?', 'Measure group sample size and uncertainty|Inspect data quality and label differences|Compare reweighting or targeted data collection|Track group metrics and overall guardrails'),
('When might oversampling a rare class produce misleading validation results?', 'Keep oversampling within training folds|Explain duplicate leakage|Account for altered class priors and calibration|Evaluate on natural prevalence'),
('Compare L1 and L2 regularization for a model with many weak correlated signals.', 'Explain sparsity versus shrinkage|Discuss correlated-feature selection behavior|Tune penalty on validation data|Relate the choice to stability and prediction goals'),
('A clustering algorithm produces attractive plots. How would you determine whether the clusters are useful?', 'Test stability across samples and seeds|Compare internal metrics cautiously|Validate against a downstream use case|Inspect interpretability and actionable differences'),
('How would you test whether a model improvement is real when you tried 100 configurations?', 'Recognize selection and multiple-comparison bias|Reserve a final untouched test set|Use nested validation where appropriate|Report paired uncertainty and practical effect size'),
('An online ranking system only observes clicks on displayed items. What problem does that create for training?', 'Identify exposure and position bias|Describe logged propensities or exploration|Discuss counterfactual evaluation assumptions|Address support and variance limitations'),
('A stakeholder interprets a SHAP value as the causal effect of changing a feature. How would you respond?', 'Explain prediction attribution|Distinguish observational correlation from intervention|Discuss feature dependence and background data|Suggest causal identification or experimentation'),
('How would you design monitoring for a model whose labels arrive six weeks late?', 'Monitor immediate data and score health|Use leading indicators with caveats|Backfill performance by prediction cohort|Define alert, investigation, and rollback actions'),
('For a binary classifier, explain a case where ROC-AUC looks strong but the deployed model is impractical.', 'Discuss extreme imbalance|Focus on precision at relevant recall|Include workload and false-positive costs|Choose deployment-specific metrics'),
('You need a model to run in 10 milliseconds on a CPU. How would this change your workflow?', 'Benchmark end-to-end latency including features|Compare small models and distillation|Measure tail latency under load|Balance predictive utility with resource constraints'),
('What are the consequences of fitting a text vocabulary before a train-test split?', 'Identify information from the test distribution|Fit learned preprocessing in the training pipeline|Distinguish unlabeled transductive assumptions|Validate the exact deployment setting'),
('A regression model systematically underpredicts the largest values. How would you diagnose this?', 'Inspect residuals by target range|Consider target transforms and loss weighting|Check training coverage and extrapolation|Compare business costs and calibration by segment'),
('How would you distinguish data drift, label shift, and concept drift in a deployed churn model?', 'Define changes in inputs, priors, and conditional outcomes|Use available labels to test hypotheses|Recognize identifiability limits|Connect each hypothesis to a response'),
('A small randomized test and a large observational analysis disagree. How would you investigate?', 'Compare populations and estimands|Inspect randomization, compliance, and power|Examine confounding and selection|Avoid assuming sample size removes bias'),
('Explain how you would use cross-validation to tune a time-series model with lagged features.', 'Use rolling or expanding windows|Fit transformations within each window|Respect horizon and information availability|Consider a gap for overlapping targets'),
('A feature improves average performance but makes predictions unstable near a policy boundary. How would you assess it?', 'Measure local sensitivity|Evaluate decision and fairness consequences|Test robustness to plausible input noise|Consider constraints, smoothing, or feature removal'),
('You inherit a production model with no reproducible training pipeline. What would you do in the first week?', 'Recover data and model lineage|Create a reproducible baseline and evaluation|Document dependencies and feature contracts|Prioritize monitoring and safe rollback'),
])
add('AI/LLM', [
('A retrieval assistant cites documents that do not support its answer. How would you isolate the failure?', 'Separate retrieval relevance from generation faithfulness|Inspect retrieved passages and citation alignment|Build a labeled claim-support evaluation|Add abstention and monitor regressions'),
('Design an evaluation set for an internal policy-question assistant.', 'Sample real intents and difficult edge cases|Include outdated and unanswerable questions|Define correctness, grounding, and refusal rubrics|Protect a holdout and control evaluator bias'),
('When would you choose retrieval-augmented generation instead of fine-tuning for changing company knowledge?', 'Explain knowledge freshness and traceability|Distinguish knowledge access from behavioral adaptation|Discuss latency and retrieval failure modes|Propose an evaluation-based choice'),
('Your LLM answers improve with longer context until they suddenly get worse. What might be happening?', 'Discuss distractors and positional effects|Check truncation and token budgets|Evaluate evidence ordering and compression|Compare task performance and cost across lengths'),
('How would you select chunk sizes for a collection containing tables, short policies, and long reports?', 'Preserve semantic and table boundaries|Consider embedding and context budgets|Tune overlap and metadata by document type|Evaluate retrieval and final-answer quality'),
('An embedding search misses exact product identifiers. What would you change?', 'Recognize lexical versus semantic matching|Compare hybrid sparse and dense search|Preserve identifiers in normalization|Evaluate recall and reranking on targeted queries'),
('A prompt-injection instruction appears inside a retrieved document. How should an assistant handle it?', 'Treat retrieved text as untrusted data|Separate instructions from document content|Constrain tool permissions and outputs|Test adversarial cases and avoid relying on prompts alone'),
('How would you measure whether a new reranker is worth its latency?', 'Measure retrieval relevance on held-out queries|Measure downstream answer utility|Benchmark tail latency and cost|Use an online experiment with guardrails'),
('A model produces valid JSON with factually wrong values. What guarantees does structured output provide?', 'Distinguish syntactic and semantic validity|Validate types, ranges, and cross-field constraints|Ground facts in source evidence|Handle invalid or uncertain output safely'),
('Describe a fallback strategy when a primary model is rate-limited.', 'Use bounded timeouts and a total deadline|Retry or switch on retriable failures|Validate all fallback outputs consistently|Record provenance and avoid duplicate side effects'),
('How would you evaluate summarization of customer-support conversations?', 'Check factual consistency and omissions|Measure coverage of actions and unresolved issues|Use privacy-aware human review|Compare latency and usefulness by conversation type'),
('A team uses an LLM as a judge for another LLM. What biases would you investigate?', 'Test position and verbosity bias|Calibrate against independent human labels|Blind model identities and randomize order|Measure agreement and task-specific errors'),
('Explain temperature to a product manager deciding between creative drafting and factual extraction.', 'Describe sampling diversity|Distinguish randomness from factual accuracy|Relate settings to task goals|Emphasize evaluation and validation over parameter folklore'),
('An assistant must call a refund tool. Where should authorization and business rules live?', 'Enforce authorization on the server|Validate tool arguments against policy|Require appropriate user intent or approval|Make side effects idempotent and auditable'),
('How would you detect that a retrieval corpus contains conflicting policy versions?', 'Track source dates and document lineage|Retrieve and compare authoritative versions|Surface conflicts instead of inventing resolution|Define version and freshness rules'),
('You have only 50 human-labeled examples for an LLM task. How would you use them?', 'Separate development from final evaluation|Prioritize representative failure modes|Use synthetic data cautiously with review|Report uncertainty and expand labels strategically'),
('A multilingual assistant performs well in English but poorly in Chinese. How would you diagnose it?', 'Separate retrieval, tokenization, and generation effects|Create language-matched evaluation sets|Inspect translated versus native source quality|Compare multilingual embeddings and model capabilities'),
('What would you log for an LLM feature while minimizing exposure of personal information?', 'Define the minimum observability data|Redact or avoid sensitive prompt content|Set retention and access controls|Record model versions, latency, and aggregate outcomes'),
('How would you decide whether to cache LLM responses?', 'Define cache keys including model and context versions|Consider personal data isolation|Set freshness and invalidation rules|Measure hit rate, cost savings, and stale-answer risk'),
('Your agent loops between two tools without making progress. What controls would you add?', 'Set step, time, and cost budgets|Detect repeated states or tool calls|Make tool results and stop criteria clear|Provide a recoverable human handoff'),
('Compare zero-shot prompting, few-shot examples, and fine-tuning for a narrow classification task.', 'Discuss data, cost, and iteration tradeoffs|Use representative examples and stable labels|Compare with a simpler non-LLM baseline|Evaluate drift and maintenance needs'),
('A model follows the requested format only 90% of the time. How would you improve reliability?', 'Use supported schema constraints where available|Validate and boundedly repair output|Simplify the format and provide examples|Keep a safe failure path and measure success'),
('How would you evaluate an answer that is partly correct but includes one dangerous unsupported claim?', 'Use claim-level evaluation|Weight severity rather than average correctness alone|Check grounding and uncertainty|Define rejection or escalation thresholds'),
('A vector database migration changes retrieval results. How would you test it?', 'Control embedding model and normalization|Check indexing and distance configuration|Compare recall against a reference search|Run representative downstream regression tests'),
('Why can adding more few-shot examples hurt a prompt?', 'Discuss conflicting patterns and relevance|Account for context budget and placement|Check class and format imbalance|Use controlled ablations on held-out examples'),
('How would you design a user-facing abstention policy for an expert assistant?', 'Define unsupported or high-uncertainty cases|Calibrate abstention using task evidence|Provide useful next steps|Measure coverage versus error severity'),
('A model upgrade improves average benchmark scores but breaks your extraction workflow. What should block rollout?', 'Use task-specific contract and regression tests|Check field-level errors and edge cases|Pin versions and stage rollout|Define rollback criteria and preserve auditability'),
('How would you estimate the cost of an LLM feature before launch?', 'Model input, output, retrieval, and retry usage|Account for traffic and long-tail requests|Benchmark realistic workflows|Set budgets and monitor actual unit cost'),
('Explain the tradeoffs between a single strong model and a router that selects smaller models by task.', 'Discuss routing errors and complexity|Compare quality, cost, and tail latency|Evaluate complete routed workflows|Use a consistent fallback and monitoring policy'),
('An LLM-generated SQL query looks plausible. How would you safely assess it before executing it?', 'Parse and validate against an allowed schema|Use read-only credentials and resource limits|Check semantics with test cases or review|Treat model output as untrusted and avoid arbitrary execution'),
])
add('Python', [
('In pandas, compute each user\'s latest event from events(user_id, event_time, event_id), breaking timestamp ties by the largest event_id. Explain missing timestamps.', 'Sort with an explicit stable tie-breaker|Group or drop duplicates by user|State how missing timestamps are treated|Avoid mutating input unexpectedly'),
('Two DataFrames are joined on account_id and the row count triples. How would you diagnose and prevent this?', 'Inspect key uniqueness and join cardinality|Use merge validation|Check duplicate and null keys|Reconcile pre- and post-join totals'),
('A CSV has mixed time zones in an event_time column. Describe a reliable conversion and daily aggregation pipeline.', 'Parse with explicit timezone handling|Convert to the business timezone before grouping|Handle malformed or missing values explicitly|Consider daylight saving boundaries'),
('Write a pandas approach to compute a seven-day rolling total per customer, including calendar days with no events.', 'Aggregate at customer-date grain|Reindex or use a time-based rolling window|Keep customer groups isolated|Define window boundaries and missing-day semantics'),
('How would you process a 20 GB CSV on a machine with 8 GB of memory?', 'Use chunking and selected columns|Choose efficient dtypes|Maintain mergeable aggregation state|Discuss operations requiring external sorting or another engine'),
('A pandas function uses iterrows to classify ten million rows. How would you improve it and verify equivalence?', 'Use vectorized masks or joins where possible|Avoid chained assignment|Test nulls, boundary values, and dtype changes|Benchmark memory as well as runtime'),
('Given transactions(user_id, amount), return users above their group median without leaking another group\'s values.', 'Use groupby transform or an aligned join|Specify strict comparison|Handle missing values|Preserve original row alignment'),
('Explain a Python bug caused by a mutable default argument, and show how you would fix it.', 'Explain definition-time evaluation|Demonstrate state shared across calls|Use None and initialize within the function|Test repeated independent calls'),
('You receive nested JSON records with optional lists of purchases. How would you normalize them into a stable table?', 'Define the target grain|Preserve parent identifiers|Handle absent and empty lists explicitly|Validate schema and avoid accidental row loss'),
('Design a test for a function that computes conversion rate from session-level data.', 'Define numerator and denominator|Cover zero sessions, duplicates, and missing identifiers|Test valid bounds and known examples|Check grouping and timezone boundaries'),
])
add('BQ', [
('Tell me about a time you turned an ambiguous request into a measurable data-science problem.', 'Set the situation and uncertainty|Describe your responsibility|Explain clarification and prioritization actions|State a measurable result and learning'),
('Tell me about a time your analysis changed a stakeholder\'s decision.', 'Explain the original decision|Describe your analysis and personal contribution|Explain how you communicated uncertainty|Describe the decision and resulting impact'),
('Describe a time a model or analysis you built did not work as expected.', 'Describe the expectation and failure|Own your specific responsibility|Explain diagnosis and corrective actions|Share the result and what changed afterward'),
('Tell me about a time you disagreed with a teammate on a technical approach.', 'Explain the disagreement and stakes|Show how you listened and compared evidence|Describe your actions toward resolution|State the outcome and relationship learning'),
('Describe a time you had to deliver under a tight deadline.', 'Set scope and time constraints|Explain your prioritization|Describe tradeoffs and communication|State the outcome and what you would improve'),
('Tell me about a time you discovered a data-quality issue that others had missed.', 'Explain the issue and its risk|Describe how you detected and validated it|Explain your fix and stakeholder communication|Quantify impact or prevention'),
('Describe a time you influenced someone without formal authority.', 'Explain the goal and relationship|Describe your specific influence strategy|Show how you responded to concerns|State the outcome and learning'),
('Tell me about a time you explained a complex result to a nontechnical audience.', 'Describe the audience and decision|Explain how you adapted the explanation|Show how you checked understanding|Describe the action or outcome'),
('Describe a time you received difficult feedback and acted on it.', 'Explain the feedback in context|Describe your initial response and ownership|Identify concrete changes you made|Show evidence of improvement'),
('Tell me about a time you balanced rigor with a practical business need.', 'Describe the business constraint|Explain risks and acceptable uncertainty|Describe your chosen approach and safeguards|State the outcome and tradeoff learning'),
('Describe a time you took initiative outside your assigned responsibilities.', 'Explain the opportunity you noticed|Clarify your own actions and collaboration|Describe how you managed scope and risk|State the resulting impact'),
('Tell me about a time you would approach differently today.', 'Set a specific situation and your role|Describe the choices you made|Explain the outcome honestly|Give a concrete alternative grounded in learning'),
])
schema = '''accounts(account_id INTEGER PRIMARY KEY, signup_date DATE, region TEXT)
sessions(session_id INTEGER PRIMARY KEY, account_id INTEGER, started_at TIMESTAMPTZ, converted BOOLEAN)
orders(order_id INTEGER PRIMARY KEY, account_id INTEGER, ordered_at TIMESTAMPTZ, amount NUMERIC, status TEXT)
contacts(contact_id INTEGER PRIMARY KEY, account_id INTEGER, contacted_at TIMESTAMPTZ, channel TEXT)
All timestamps are instants. Amount is order revenue. Use America/New_York for local-date questions. Use PostgreSQL. Unless stated otherwise, include only status = 'paid' orders; NULL amounts contribute zero revenue.'''
sql_rows = [
('Return paid revenue per account, including accounts with no paid orders.', "SELECT a.account_id, COALESCE(SUM(o.amount),0) AS revenue FROM accounts a LEFT JOIN orders o ON o.account_id=a.account_id AND o.status='paid' GROUP BY a.account_id;", 'Use a left join from accounts|Keep paid filtering in the join|Aggregate at account grain|Return zero for missing revenue'),
('Return the three accounts with highest paid revenue. Break ties with smaller account_id.', "SELECT account_id, COALESCE(SUM(amount),0) AS revenue FROM orders WHERE status='paid' GROUP BY account_id ORDER BY revenue DESC, account_id LIMIT 3;", 'Filter paid orders|Aggregate revenue by account|Use deterministic ordering|Limit after aggregation'),
('For each New York calendar day with sessions, compute session conversion rate. A NULL converted value counts as false.', "SELECT (started_at AT TIME ZONE 'America/New_York')::date AS day, AVG(CASE WHEN converted IS TRUE THEN 1.0 ELSE 0.0 END) AS rate FROM sessions GROUP BY 1;", 'Convert to the local timezone|Use all sessions as denominator|Avoid integer division|Handle NULL conversion explicitly'),
('Find accounts that have sessions but no paid orders.', "SELECT a.account_id FROM accounts a WHERE EXISTS (SELECT 1 FROM sessions s WHERE s.account_id=a.account_id) AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.account_id=a.account_id AND o.status='paid');", 'Require at least one session|Use a correct anti-join or NOT EXISTS|Apply paid status inside the order condition|Avoid duplicate accounts'),
('Return each account\'s most recent paid order, breaking timestamp ties by larger order_id.', "SELECT order_id,account_id,ordered_at,amount FROM (SELECT o.*, ROW_NUMBER() OVER(PARTITION BY account_id ORDER BY ordered_at DESC,order_id DESC) AS rn FROM orders o WHERE status='paid') t WHERE rn=1;", 'Partition by account|Filter paid orders|Specify a deterministic tie-breaker|Select exactly one row per account'),
('Find accounts with at least two paid orders in August 2026, measured in New York time.', "SELECT account_id FROM orders WHERE status='paid' AND ordered_at >= TIMESTAMPTZ '2026-08-01 00:00 America/New_York' AND ordered_at < TIMESTAMPTZ '2026-09-01 00:00 America/New_York' GROUP BY account_id HAVING COUNT(*)>=2;", 'Use local-month instant boundaries|Use an exclusive upper bound|Filter paid orders|Filter groups with HAVING'),
('For each region, return the count of accounts and count of accounts with any paid order, without double counting.', "SELECT a.region,COUNT(*) AS accounts,COUNT(*) FILTER(WHERE EXISTS(SELECT 1 FROM orders o WHERE o.account_id=a.account_id AND o.status='paid')) AS buyers FROM accounts a GROUP BY a.region;", 'Preserve account grain|Avoid order join fanout|Count buyers once|Group by region'),
('For each account with paid orders, compute the time in hours between successive paid orders.', "SELECT account_id,order_id,EXTRACT(EPOCH FROM (ordered_at-LAG(ordered_at) OVER(PARTITION BY account_id ORDER BY ordered_at,order_id)))/3600.0 AS gap_hours FROM orders WHERE status='paid';", 'Use LAG within account|Order deterministically|Convert interval to hours|Keep the first gap NULL'),
('Return New York daily paid revenue and cumulative paid revenue for days with paid orders.', "WITH daily AS (SELECT (ordered_at AT TIME ZONE 'America/New_York')::date AS day,COALESCE(SUM(amount),0) AS revenue FROM orders WHERE status='paid' GROUP BY 1) SELECT day,revenue,SUM(revenue) OVER(ORDER BY day ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative FROM daily ORDER BY day;", 'Aggregate at local-day grain first|Filter paid orders|Use an explicit running window|Order output by date'),
('Find accounts with both email and LinkedIn contacts; other channels are allowed.', "SELECT account_id FROM contacts GROUP BY account_id HAVING COUNT(*) FILTER(WHERE channel='email')>0 AND COUNT(*) FILTER(WHERE channel='linkedin')>0;", 'Group at account grain|Require both channels|Allow other channels|Avoid requiring exactly two total rows'),
('Compute mean paid order value per region, returning zero for regions with no paid orders.', "SELECT a.region,COALESCE(AVG(COALESCE(o.amount,0)) FILTER(WHERE o.order_id IS NOT NULL),0) AS aov FROM accounts a LEFT JOIN orders o ON o.account_id=a.account_id AND o.status='paid' GROUP BY a.region;", 'Use order-level rather than account-level mean|Preserve regions without orders|Treat NULL amount as zero|Do not count synthetic left-join rows'),
('Find paid orders whose amount is greater than that account\'s mean paid order amount. Treat NULL amount as zero.', "SELECT order_id,account_id,amount FROM (SELECT o.*,AVG(COALESCE(amount,0)) OVER(PARTITION BY account_id) AS mean_amount FROM orders o WHERE status='paid') t WHERE COALESCE(amount,0)>mean_amount;", 'Compute per-account mean|Use paid orders consistently|Apply strict greater-than comparison|Handle NULL amount consistently'),
('For accounts with paid orders, rank revenue within each region; equal revenue should share a rank with no gaps.', "WITH r AS (SELECT a.account_id,a.region,COALESCE(SUM(o.amount),0) AS revenue FROM accounts a JOIN orders o ON o.account_id=a.account_id AND o.status='paid' GROUP BY a.account_id,a.region) SELECT *,DENSE_RANK() OVER(PARTITION BY region ORDER BY revenue DESC) AS rank FROM r;", 'Aggregate before ranking|Partition by region|Use DENSE_RANK|Do not break revenue ties in the rank expression'),
('Return all New York dates from August 1 through August 7, 2026 with paid revenue, including zero-revenue days.', "WITH dates AS (SELECT d::date AS day FROM generate_series(TIMESTAMP '2026-08-01',TIMESTAMP '2026-08-07',INTERVAL '1 day') d), revenue AS (SELECT (ordered_at AT TIME ZONE 'America/New_York')::date AS day, SUM(amount) AS revenue FROM orders WHERE status='paid' GROUP BY 1) SELECT d.day,COALESCE(r.revenue,0) AS revenue FROM dates d LEFT JOIN revenue r USING(day) ORDER BY d.day;", 'Generate the complete date spine|Aggregate orders before joining|Use New York dates|Fill absent totals with zero'),
('Find accounts with a paid order on the New York calendar date of signup.', "SELECT a.account_id FROM accounts a WHERE EXISTS(SELECT 1 FROM orders o WHERE o.account_id=a.account_id AND o.status='paid' AND (o.ordered_at AT TIME ZONE 'America/New_York')::date=a.signup_date);", 'Compare dates in the business timezone|Use paid orders|Return one row per account|Compare with the signup date'),
('For each contact, return whether a paid order occurred in the next 48 hours, including the contact instant but excluding the 48-hour endpoint.', "SELECT c.contact_id,EXISTS(SELECT 1 FROM orders o WHERE o.account_id=c.account_id AND o.status='paid' AND o.ordered_at>=c.contacted_at AND o.ordered_at<c.contacted_at+INTERVAL '48 hours') AS followed_by_order FROM contacts c;", 'Keep one row per contact|Match the account|Use correct half-open time bounds|Avoid confusing association with causal attribution'),
('Compute the percentage of all paid revenue contributed by each account, returning NULL if total revenue is zero.', "WITH r AS (SELECT account_id,COALESCE(SUM(amount),0) AS revenue FROM orders WHERE status='paid' GROUP BY account_id) SELECT account_id,100.0*revenue/NULLIF(SUM(revenue) OVER(),0) AS percent FROM r;", 'Aggregate account revenue|Compute global revenue with a window|Avoid integer division|Guard division by zero'),
('Find accounts with at least three consecutive New York calendar days containing sessions.', "WITH dates AS (SELECT DISTINCT account_id,(started_at AT TIME ZONE 'America/New_York')::date AS day FROM sessions), islands AS (SELECT account_id,day-(ROW_NUMBER() OVER(PARTITION BY account_id ORDER BY day))::integer AS island FROM dates) SELECT DISTINCT account_id FROM islands GROUP BY account_id,island HAVING COUNT(*)>=3;", 'Deduplicate account-date pairs|Use a gaps-and-islands approach|Respect local dates|Return accounts with a run of at least three'),
('For each region, return account count, session count, and paid revenue without multiplying values through joins.', "WITH s AS (SELECT account_id,COUNT(*) AS n FROM sessions GROUP BY account_id),o AS (SELECT account_id,COALESCE(SUM(amount),0) AS revenue FROM orders WHERE status='paid' GROUP BY account_id) SELECT a.region,COUNT(*) AS accounts,COALESCE(SUM(s.n),0) AS sessions,COALESCE(SUM(o.revenue),0) AS revenue FROM accounts a LEFT JOIN s USING(account_id) LEFT JOIN o USING(account_id) GROUP BY a.region;", 'Preaggregate both fact tables|Join at account grain|Keep accounts without activity|Coalesce missing totals'),
('For every account with paid orders, return its second paid order. Use order_id to break ascending timestamp ties.', "SELECT account_id,order_id,ordered_at FROM (SELECT account_id,order_id,ordered_at,ROW_NUMBER() OVER(PARTITION BY account_id ORDER BY ordered_at,order_id) AS rn FROM orders WHERE status='paid') t WHERE rn=2;", 'Use ROW_NUMBER by account|Filter paid orders before ranking|Specify ascending deterministic ordering|Exclude accounts with fewer than two orders'),
]
for i,(prompt,query,points) in enumerate(sql_rows,1):
    questions.append(dict(id=f'sql-{i:02}',category='SQL',difficulty='Hard' if i>=14 else 'Medium',prompt=prompt,rubric=points.split('|'),schema=schema,expectedQuery=query))
(ROOT/'data/questions.json').write_text(json.dumps(questions,ensure_ascii=False,indent=2)+'\n')
(ROOT/'data/bq.json').write_text(json.dumps([q for q in questions if q['category']=='BQ'],ensure_ascii=False,indent=2)+'\n')
rows = ',\n'.join("('%s', '%s', '%s'::jsonb)"%(q['id'],q['category'],json.dumps(q,ensure_ascii=False).replace("'","''")) for q in questions)
(ROOT/'supabase/seed.sql').write_text('-- Original questions authored for Offer Quest. Safe to run repeatedly.\nINSERT INTO public.question_bank (id, category, content) VALUES\n'+rows+'\nON CONFLICT (id) DO UPDATE SET category=EXCLUDED.category, content=EXCLUDED.content;\n')
print({c:sum(q['category']==c for q in questions) for c in ['ML','AI/LLM','SQL','Python','BQ']})
